spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456

    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true

  # 热部署生效spring:
  # 设置重启的目录,添加那个目录的文件需要restart
  # 为mybatis设置，生产环境可删除
  # 排除那个目录的文件不需要restart
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

  # Redis配置
  # Redis数据库索引（默认为0）
  # Redis服务器地址:
  # Redis服务器连接端口
  # Redis服务器连接密码（默认为空）
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 3
    jedis:
      pool:
        max-active: 10
        max-idle: 10
        max-wait: 3

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    # 消费者数量
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10
        # 消费者每次从消息队列获取的消息数量
        prefetch: 1
        # 消费者自启
        auto-startup: true
        # 消费失败，自动重新入队
        default-requeue-rejected: true
    # 启用发送重试
    template:
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 3
        multiplier: 1.0

server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8



